---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: tfswitch --version
    register: tfswitch_test_output
  - debug:
      msg: '{{ tfswitch_test_output.stdout }}'
  - command: terraform-switcher --version
    register: terraform_switcher_test_output
  - debug:
      msg: '{{ terraform_switcher_test_output.stdout }}'
