---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for existing install in {{ terraform_switcher_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ terraform_switcher_install_dir }}'
  changed_when: false
  register: terraform_switcher_binary
- name: Downloading and installing terraform-switcher
  when: not terraform_switcher_binary.stat.exists
  block:
    - name: Downloading {{ terraform_switcher_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ terraform_switcher_url }}'
        dest: '{{ terraform_switcher_tmp_archive }}'
        mode: '644'
        checksum: '{{ terraform_switcher_checksum }}'
    - name: Mkdir {{ terraform_switcher_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ terraform_switcher_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ terraform_switcher_tmp_archive }}...
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ terraform_switcher_tmp_archive }}'
        dest: '{{ terraform_switcher_install_dir }}'
        creates: '{{ terraform_switcher_install_dir }}/terraform-switcher'
  always:
    - name: Rm {{ terraform_switcher_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ terraform_switcher_tmp_archive }}'
        state: absent
- name: Linking..
  become: true
  become_user: root
  with_items:
    - tfswitch
  ansible.builtin.file:
    src: '{{ terraform_switcher_install_dir }}/{{ item }}'
    dest: '{{ terraform_switcher_parent_install_dir }}/bin/{{ item }}'
    state: link
